name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    paths:
      - 'app/**'
    branches:
      - master

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Unit tests
        run: |
          chmod +x ./gradlew
          sudo ./gradlew test
