name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Unit tests
        run: |
          chmod +x ./gradlew
          sudo ./gradlew test
